version: '3.8'

services:
  node:
    build:
      context: .
      dockerfile: ./.docker/node/Dockerfile
    command: 'npm run dev'
    volumes:
      - ./:/var/www/frontend
      - node_modules_frontend:/var/www/node_modules
    ports:
      - 5173:5173
volumes:
  node_modules_frontend:
